### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by cvpfus** [rotem154154/self-driving-car#2]
I got this message when running main.py

Traceback (most recent call last):
  File "D:/Source code/self-driving-car-master/self-driving-car-master/main.py", line 135, in <module>
    map = CarMap()
  File "D:\Source code\self-driving-car-master\self-driving-car-master\Car_Map.py", line 13, in __init__
    self.in_grey = [160] * (len(self.in_map) / 2)
TypeError: can't multiply sequence by non-int of type 'float'

I'm totally newbie

**Comment by rotem154154** [comment]
try to run it with python 2.7
